/* GENERATED by BBMcuhub.Gen.WireGen — do not edit. schedule.gen.h
   per-port {period_us, last_us, tick} for wheels (§08) */
/* Generated from wheels's contract rates. The actuator floor runs every
   loop (period 0) and is added by the firmware, not listed here. */

static Task tasks[] = {
  { 20000, 0, motor_left_cmd_tick }  /* motor_left @ 50 Hz */,
  { 20000, 0, status_left_sample_tick }  /* status_left @ 50 Hz */,
  { 20000, 0, status_right_sample_tick }  /* status_right @ 50 Hz */,
  { 20000, 0, motor_right_cmd_tick }  /* motor_right @ 50 Hz */
};
#define N_TASKS (sizeof(tasks) / sizeof(tasks[0]))
