/* GENERATED by BBMcuhub.Gen.WireGen — do not edit. wire_contract.h
   ids · structs · floor window · hash */
#ifndef BB_MCUHUB_WIRE_CONTRACT_H
#define BB_MCUHUB_WIRE_CONTRACT_H

#include <stdint.h>
#include <stdbool.h>

/* The CRC-covered body header, before every payload (§03). t_dev is
   per-port (§04): an unstamped port omits it. */
#define WIRE_HEADER_BASE_SIZE 4
#define WIRE_HEADER_STAMPED_SIZE 12
#define WIRE_BROADCAST_NODE 0x00

/* The root hub's children-facing backplane transport (a contract fact, not
   a build flag — see docs/adr/0002). 1 = a plain UART carrying the same
   COBS+CRC frames (no CAN segmentation: a wide body rides one frame); 0 =
   the default CAN/TWAI backplane. For v1 the backplane is uniform per robot:
   UART iff any non-root hub is reached over :uart. */
#define BACKPLANE_TRANSPORT_UART 0

/* Port ids — generated, stable, never hand-assigned (§06). */
#define PORT_IMU_POSE 0xEF
#define PORT_MOTOR_MOTOR_TARGET 0x28
#define PORT_MOTOR_MOTOR_STATUS 0xDE

/* Which ports carry t_dev (1) vs omit it (0) — see §04. */
#define PORT_IMU_POSE_STAMPED 1
#define PORT_MOTOR_MOTOR_TARGET_STAMPED 0
#define PORT_MOTOR_MOTOR_STATUS_STAMPED 0

/* Decode-time lookup: does the frame for (node, port) carry t_dev? The
   inbound path peeks the base header for (node, port), then calls this to
   learn the header shape — exactly as the host learns it from PortIndex. */
static inline bool wire_port_stamped(uint8_t node, uint8_t port) {
    if (node == 0x02 && port == 0xEF) return true;
  return false;
}

/* Packed value structs — field order MATCHES Contract.Layouts (§06). */
typedef struct __attribute__((packed)) {
  float nm;
} Effort;

typedef struct __attribute__((packed)) {
  float qw;
  float qx;
  float qy;
  float qz;
  float wx;
  float wy;
  float wz;
  float ax;
  float ay;
  float az;
} Imu;

typedef struct __attribute__((packed)) {
  uint16_t applied_seq;
  bool floored;
} Status;

/* Per-actuator floor window, derived from one number (§05). */
#define FLOOR_MISSES_MOTOR_MOTOR_TARGET 5
#define CMD_PERIOD_MS_MOTOR_MOTOR_TARGET 20

/* Contract hash — the drift test compares this. */
#define WIRE_CONTRACT_SHA "58f56de36eaf7b86"

#endif /* BB_MCUHUB_WIRE_CONTRACT_H */
