/* GENERATED by BBMcuhub.Gen.WireGen — do not edit. schedule.gen.h
   per-port {period_us, last_us, tick} for blaster (§08) */
/* Generated from blaster's contract rates. The actuator floor runs every
   loop (period 0) and is added by the firmware, not listed here. */

static Task tasks[] = {
  { 50000, 0, range_front_sample_tick }  /* range_front @ 20 Hz */,
  { 50000, 0, status_led_cmd_tick }  /* status_led @ 20 Hz */,
  { 10000, 0, pose_sample_tick }  /* pose @ 100 Hz */
};
#define N_TASKS (sizeof(tasks) / sizeof(tasks[0]))
