/* GENERATED by BBMcuhub.Gen.WireGen — do not edit. schedule.gen.h
   per-port {period_us, last_us, tick} for motor (§08) */
/* Generated from motor's contract rates. The actuator floor runs every
   loop (period 0) and is added by the firmware, not listed here. */

static Task tasks[] = {
  { 20000, 0, motor_target_cmd_tick }  /* motor_target @ 50 Hz */,
  { 20000, 0, motor_status_sample_tick }  /* motor_status @ 50 Hz */
};
#define N_TASKS (sizeof(tasks) / sizeof(tasks[0]))
