/* GENERATED by BBMcuhub.Gen.WireGen — do not edit. schedule.gen.h
   per-port {period_us, last_us, tick} for imu (§08) */
/* Generated from imu's contract rates. The actuator floor runs every
   loop (period 0) and is added by the firmware, not listed here. */

static Task tasks[] = {
  { 20000, 0, pose_sample_tick }  /* pose @ 50 Hz */
};
#define N_TASKS (sizeof(tasks) / sizeof(tasks[0]))
